[COMMON]
; data_file =  ../data/2_4s.dat
data_file =  ../data/mavi202412/mavi20241209_200w_dataset.dat
; data_file =  ../data/mavi202512/mavi20250325_200w_dataset.dat
; data_file =  ../data/mavi202512/mavi20251230_200w_dataset.dat
; data_file =  ../data/mavi202601/mavi202601_200w_dataset.dat
; data_file =  ../data/caida_200w_dataset.dat

; 设置IFPD的阈值
; IFPD < delay_thres：被视为“正常流量”或“短延迟流量”。
; IFPD ≥ delay_thres：被视为“异常流量”、“攻击流量”（如 LDDoS）或“长延迟流量”。
; delay_thres = 600000        
delay_thres = 600000   

mem_size = 800000

[FDFilter]
k = 8          ; k bitBF
kk = 2          ; kk-bit counter

; k = 8 settings
; nbits = 80977
; nbits = 126488
; nbits = 172000
nbits = 2000000

num_hash = 6
gnbits = 1300000
gnum_hash = 6


[MergeableFDFIlter]
k = 7
kk = 2

; settings for k=7
nbits = 66254
; nbits = 103490
; nbits = 140727
; nbits = 177963

num_hash = 6
gnbits = 1000000
gnum_hash = 6


