[COMMON]
data_file =  ../data/mavi20241209_200w_dataset.dat


; 设置IFPD的阈值
delay_thres = 600000   

mem_size = 800000

[LFFilter]
n_hot = 3
n_warm = 10
n_cold = 4
k_w = 3       
heavy_thres = 2
slots = 250000
fp_bits = 7
win_id_bits = 2 



